### PR TITLE
fix navbar issue

### PR DESCRIPTION
**Pull request by lakshita10341**
I have fixed the navbar hovering issue. please check the pr.

### CODE REVIEW

**Comment by pradipbhatt** [comment]
**@lakshita10341 it's not solved yet !**
[Screencast from 2024-10-18 08-09-40.webm](https://github.com/user-attachments/assets/c1fea851-b94f-47b0-ac17-d83feda2f4ae)

- it's not clickable while hover.

onhover: make underline on the navkinks with light smooth effect

**Comment by lakshita10341** [comment]
sorry....i will fix this

**Comment by pradipbhatt** [comment]
> sorry....i will fix this

it's okae try if had any problem you may ask me as well !
Happy coding <3

**Comment by lakshita10341** [comment]
Has the issue been fixed or do I need to fix it as the issue has been closed?

**Comment by pradipbhatt** [comment]
> Has the issue been fixed or do I need to fix it as the issue has been closed?

it's not still make the onhover underline effect on navlinks

**Comment by lakshita10341** [comment]
I've fixed the CSS issue using JavaScript functions. Please review it.

**Comment by pradipbhatt** [comment]
> I've fixed the CSS issue using JavaScript functions. Please review it.

PR merged @lakshita10341

**Pull request merged**
